# Generated by Django 4.0.6 on 2022-10-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_card_card_alter_customer_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='account_balance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Faulu', 'Mshwari'), ('Tala', 'fuliza')], max_length=10, null=True),
        ),
    ]
