# Generated by Django 4.0.6 on 2022-10-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_balance_account_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='account_number',
        ),
    ]
