# Generated by Django 4.0.6 on 2022-10-23 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rename_account_id_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
