# Generated by Django 4.0.6 on 2022-10-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_account_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loan_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.loan'),
        ),
    ]
