# Generated by Django 4.0.6 on 2022-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_account_loan_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_Id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_term',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='walletb',
        ),
    ]
