# Generated by Django 4.0.6 on 2022-10-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_remove_loan_loan_id_remove_loan_loan_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountA', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='loan_balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Loan', to='wallet.loan'),
        ),
    ]
