# Generated by Django 4.0.6 on 2022-10-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_loan_account_alter_account_loan_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='loan_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='loan_balance2',
            field=models.IntegerField(null=True),
        ),
    ]
